### ISSUE TITLE
Adjusting the speed of the directional input

### ISSUE THREAD

**Issue by JappaWakka** [zach-morris/same_cdi#11]
Hi there! I love that it's possible to play cdi games on my phone. However, the speed at which the cursor moves is terribly slow. There's no way to change the speed of the directional input on android. Could there be a settings option for that?

**Comment by zach-morris** [comment]
There aren't any switches i see that are already available for this.  However, it's built off MAME, so if you can bring up the MAME config menu (by hitting tab usually, not sure how to do what without a keyboard) you can change mouse sensitivity options there
<img width="731" alt="Screen Shot 2022-08-04 at 12 48 55 PM" src="https://user-images.githubusercontent.com/12554283/182940225-c8a32e60-c632-48fd-9278-156e704b160e.png">
.

**Comment by JappaWakka** [comment]
You're right! There's an overlay in retroarch that is basically an on-screen keyboard! Pressing tab on that shows the menu! Thanks :D
