### ISSUE TITLE
NVRam file for individual games.

### ISSUE THREAD

**Issue by sionisaac** [zach-morris/same_cdi#3]
Is there any way to get same_cdi to use per game NVRam files?  I've been testing this core a lot and have noticed that the NVRam file fills up quite quickly especially if you play lots of different software.  Sometimes when you load software the cdi system tells you that there is no free memory.  And shows you the memory manager but controls do not work here and there is zero functionality.  The only way to get it back working is to delete/rename the NVRam file in RetroArch/Saves and restart the core so that it creates a new file.  Is there a fix for this?

Also can this core be built for Raspberry Pi specifically retropie?  I keep checking the nightly section but still now core updates for armhf.

**Comment by zach-morris** [comment]
Added via https://github.com/zach-morris/same_cdi/commit/138d6653e178e7fb91704de585d8a515e8c3402d
Nvram is now saved in a subdirectory within nvram, named per game
