### ISSUE TITLE
Provide hash/sha for required bios files

### ISSUE THREAD

**Issue by ryanchauvin** [zach-morris/same_cdi#8]
Can you please provide the sha hash for each bios file that's required?
![image](https://user-images.githubusercontent.com/19695896/175750877-b68cd4bd-7dd2-4cc4-b3ca-5bfb9a57e943.png)

**Comment by zach-morris** [comment]
I didn't do this originally as this core in theory would be tied to MAME versions (although this core would only be updated if/when cdi functionality updates), and those change often enough that version control of bios files could be difficult.  Current version of the core is based on MAME 243/244 (the bios files are the same for these MAME versions).  It might be best just to mention what version the core is based on.

**Comment by ryanchauvin** [comment]
that's perfect!!!!!! I just found the [mame0244.xml](https://github.com/mamedev/mame/releases/download/mame0244/mame0244lx.zip) that lists the bios name, CRC, and sha1. Thanks for pointing this out :)
